### PR TITLE
Add alternative syntax for ordered lists

### PR DESCRIPTION
**Pull request by SoulPrudya**

### CODE REVIEW

**Comment by karlb** [comment]
The implementation is simple and it conforms to CommonMark. So the main question is: Is it worth having two redundant syntaxes for ordered lists?

I've never used this syntax myself (even in other markdown-like implementations). Does anyone have insights on how often other people use this? Or general opinions on this?

**Review by N-R-K — APPROVED** [review]
I've also never used `)` syntax. But since it's specified in commonmark and is a simple enough change, I don't see why not.

**Comment by SoulPrudya** [comment]
I think it's not bad to have two syntaxes because it increases CommonMark's compatibility. And code complexity will not change.

**Comment by karlb** [comment]
Thanks for the PR and the feedback!

**Pull request merged**
